#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_P001_0

#include "Basic.hpp"

#include "ABP_Player_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_P001.ABP_P001_C
// 0x0000 (0xA050 - 0xA050)
class ABP_P001_0::UABP_P001_C final : public UABP_Player_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimBlueprintGeneratedClass ABP_P001.ABP_P001_C", true, "ABP_P001_C">();
	}
	static class ABP_P001_0::UABP_P001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_P001_0::UABP_P001_C>();
	}
};
static_assert(alignof(ABP_P001_0::UABP_P001_C) == 0x000010, "Wrong alignment on ABP_P001_0::UABP_P001_C");
static_assert(sizeof(ABP_P001_0::UABP_P001_C) == 0x00A050, "Wrong size on ABP_P001_0::UABP_P001_C");

}

