#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_N016

#include "Basic.hpp"

#include "ABP_NPC_BASE_Ex_SimpleTurn_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_N016.ABP_N016_C
// 0x0000 (0x59B0 - 0x59B0)
class UABP_N016_C final : public UABP_NPC_BASE_Ex_SimpleTurn_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_N016_C">();
	}
	static class UABP_N016_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_N016_C>();
	}
};
static_assert(alignof(UABP_N016_C) == 0x000010, "Wrong alignment on UABP_N016_C");
static_assert(sizeof(UABP_N016_C) == 0x0059B0, "Wrong size on UABP_N016_C");

}

