#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Dead

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "DarwinGame_structs.hpp"


namespace SDK::Params
{

// Function Action_Dead.Action_Dead_C.GetTargetRotation
// 0x0094 (0x0094 - 0x0000)
struct Action_Dead_C_GetTargetRotation final
{
public:
	struct FRotator                               ReturnValue;                                       // 0x0000(0x000C)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	struct FActionResult                          CallFunc_GetActionResult_ReturnValue;              // 0x000C(0x0030)(ConstParm, NoDestructor)
	bool                                          CallFunc_BlowToAttackerDirection_ReturnValue;      // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0040(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_SelectVector_ReturnValue;                 // 0x004C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_FindLookAtRotation_ReturnValue;           // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_FindLookAtRotation_ReturnValue_1;         // 0x0064(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_SelectRotator_ReturnValue;                // 0x0070(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0088(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Action_Dead_C_GetTargetRotation) == 0x000004, "Wrong alignment on Action_Dead_C_GetTargetRotation");
static_assert(sizeof(Action_Dead_C_GetTargetRotation) == 0x000094, "Wrong size on Action_Dead_C_GetTargetRotation");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, ReturnValue) == 0x000000, "Member 'Action_Dead_C_GetTargetRotation::ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_GetActionResult_ReturnValue) == 0x00000C, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_GetActionResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_BlowToAttackerDirection_ReturnValue) == 0x00003C, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_BlowToAttackerDirection_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000040, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_SelectVector_ReturnValue) == 0x00004C, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_SelectVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_FindLookAtRotation_ReturnValue) == 0x000058, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_FindLookAtRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_FindLookAtRotation_ReturnValue_1) == 0x000064, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_FindLookAtRotation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_SelectRotator_ReturnValue) == 0x000070, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_SelectRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_BreakRotator_Roll) == 0x00007C, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_BreakRotator_Pitch) == 0x000080, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_BreakRotator_Yaw) == 0x000084, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetTargetRotation, CallFunc_MakeRotator_ReturnValue) == 0x000088, "Member 'Action_Dead_C_GetTargetRotation::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");

// Function Action_Dead.Action_Dead_C.IsTakenFromFront
// 0x0070 (0x0070 - 0x0000)
struct Action_Dead_C_IsTakenFromFront final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActionResult                          CallFunc_GetActionResult_ReturnValue;              // 0x0004(0x0030)(ConstParm, NoDestructor)
	struct FVector                                CallFunc_GetActorForwardVector_ReturnValue;        // 0x0034(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BlowToAttackerDirection_ReturnValue;      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0044(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_SelectVector_ReturnValue;                 // 0x0050(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x005C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Dot_VectorVector_ReturnValue;             // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x006C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Action_Dead_C_IsTakenFromFront) == 0x000004, "Wrong alignment on Action_Dead_C_IsTakenFromFront");
static_assert(sizeof(Action_Dead_C_IsTakenFromFront) == 0x000070, "Wrong size on Action_Dead_C_IsTakenFromFront");
static_assert(offsetof(Action_Dead_C_IsTakenFromFront, ReturnValue) == 0x000000, "Member 'Action_Dead_C_IsTakenFromFront::ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_IsTakenFromFront, CallFunc_GetActionResult_ReturnValue) == 0x000004, "Member 'Action_Dead_C_IsTakenFromFront::CallFunc_GetActionResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_IsTakenFromFront, CallFunc_GetActorForwardVector_ReturnValue) == 0x000034, "Member 'Action_Dead_C_IsTakenFromFront::CallFunc_GetActorForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_IsTakenFromFront, CallFunc_BlowToAttackerDirection_ReturnValue) == 0x000040, "Member 'Action_Dead_C_IsTakenFromFront::CallFunc_BlowToAttackerDirection_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_IsTakenFromFront, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000044, "Member 'Action_Dead_C_IsTakenFromFront::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_IsTakenFromFront, CallFunc_SelectVector_ReturnValue) == 0x000050, "Member 'Action_Dead_C_IsTakenFromFront::CallFunc_SelectVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_IsTakenFromFront, CallFunc_Subtract_VectorVector_ReturnValue) == 0x00005C, "Member 'Action_Dead_C_IsTakenFromFront::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_IsTakenFromFront, CallFunc_Dot_VectorVector_ReturnValue) == 0x000068, "Member 'Action_Dead_C_IsTakenFromFront::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_IsTakenFromFront, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x00006C, "Member 'Action_Dead_C_IsTakenFromFront::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");

// Function Action_Dead.Action_Dead_C.GetReaction
// 0x0038 (0x0038 - 0x0000)
struct Action_Dead_C_GetReaction final
{
public:
	EDamageReactionType                           ReactionType;                                      // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDamageReactionType                           BaseReaction;                                      // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActionResult                          CallFunc_GetActionResult_ReturnValue;              // 0x0004(0x0030)(ConstParm, NoDestructor)
	bool                                          CallFunc_IsResistToBlown_ReturnValue;              // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EDamageReactionType                           CallFunc_GetReactionType_ReturnValue;              // 0x0036(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0037(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Action_Dead_C_GetReaction) == 0x000004, "Wrong alignment on Action_Dead_C_GetReaction");
static_assert(sizeof(Action_Dead_C_GetReaction) == 0x000038, "Wrong size on Action_Dead_C_GetReaction");
static_assert(offsetof(Action_Dead_C_GetReaction, ReactionType) == 0x000000, "Member 'Action_Dead_C_GetReaction::ReactionType' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetReaction, BaseReaction) == 0x000001, "Member 'Action_Dead_C_GetReaction::BaseReaction' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetReaction, CallFunc_GetActionResult_ReturnValue) == 0x000004, "Member 'Action_Dead_C_GetReaction::CallFunc_GetActionResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetReaction, CallFunc_IsResistToBlown_ReturnValue) == 0x000034, "Member 'Action_Dead_C_GetReaction::CallFunc_IsResistToBlown_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetReaction, CallFunc_EqualEqual_NameName_ReturnValue) == 0x000035, "Member 'Action_Dead_C_GetReaction::CallFunc_EqualEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetReaction, CallFunc_GetReactionType_ReturnValue) == 0x000036, "Member 'Action_Dead_C_GetReaction::CallFunc_GetReactionType_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_GetReaction, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000037, "Member 'Action_Dead_C_GetReaction::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

// Function Action_Dead.Action_Dead_C.Update
// 0x0004 (0x0004 - 0x0000)
struct Action_Dead_C_Update final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Action_Dead_C_Update) == 0x000004, "Wrong alignment on Action_Dead_C_Update");
static_assert(sizeof(Action_Dead_C_Update) == 0x000004, "Wrong size on Action_Dead_C_Update");
static_assert(offsetof(Action_Dead_C_Update, DeltaTime) == 0x000000, "Member 'Action_Dead_C_Update::DeltaTime' has a wrong offset!");

// Function Action_Dead.Action_Dead_C.Reaction
// 0x0001 (0x0001 - 0x0000)
struct Action_Dead_C_Reaction final
{
public:
	EDamageReactionType                           Type;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Action_Dead_C_Reaction) == 0x000001, "Wrong alignment on Action_Dead_C_Reaction");
static_assert(sizeof(Action_Dead_C_Reaction) == 0x000001, "Wrong size on Action_Dead_C_Reaction");
static_assert(offsetof(Action_Dead_C_Reaction, Type) == 0x000000, "Member 'Action_Dead_C_Reaction::Type' has a wrong offset!");

// Function Action_Dead.Action_Dead_C.ExecuteUbergraph_Action_Dead
// 0x02D0 (0x02D0 - 0x0000)
struct Action_Dead_C_ExecuteUbergraph_Action_Dead final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          Temp_object_Variable;                              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class ICharacterMovementInterfaceForABP> K2Node_DynamicCast_AsCharacter_Movement_Interface_for_ABP; // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Temp_string_Variable;                              // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaTime;                            // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface;          // 0x0040(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_1;        // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_1;            // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class ICharacterInterface>   CallFunc_GetCurrentMoveStateTag_self_CastInput;    // 0x0080(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FGameplayTag                           CallFunc_GetCurrentMoveStateTag_ReturnValue;       // 0x0090(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess;   // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9A[0x6];                                       // 0x009A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          Temp_object_Variable_1;                            // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDamageReactionType                           K2Node_CustomEvent_Type;                           // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x00A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AA[0x2];                                       // 0x00AA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_GetEnumeratorName_ReturnValue;            // 0x00AC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Split_LeftS;                              // 0x00D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Split_RightS;                             // 0x00E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Split_ReturnValue;                        // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x00F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsTakenFromFront_ReturnValue;             // 0x0109(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_10A[0x6];                                      // 0x010A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_2;        // 0x0110(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_122[0x6];                                      // 0x0122(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_3;        // 0x0128(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_139[0x7];                                      // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_2;            // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_4;        // 0x0148(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15A[0x6];                                      // 0x015A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_5;        // 0x0160(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_171[0x7];                                      // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_6;        // 0x0178(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ExecuteAbility_ReturnValue;               // 0x0189(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_18A[0x6];                                      // 0x018A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_7;        // 0x0190(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_8;                     // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A1[0x7];                                      // 0x01A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_3;            // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_GetTargetRotation_ReturnValue;            // 0x01B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_SetActorRotation_ReturnValue;          // 0x01BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EDamageReactionType                           CallFunc_GetReaction_ReactionType;                 // 0x01BD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x01BE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1BF[0x1];                                      // 0x01BF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_8;        // 0x01C0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_9;                     // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D1[0x7];                                      // 0x01D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_9;        // 0x01D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_10;                    // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class ICharacterInterface>   CallFunc_GetLinkType_self_CastInput;               // 0x01F0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ELinkType                                     CallFunc_GetLinkType_ReturnValue;                  // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_201[0x3];                                      // 0x0201(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActionResult                          CallFunc_GetActionResult_ReturnValue;              // 0x0204(0x0030)(ConstParm, NoDestructor)
	struct FVector                                CallFunc_GetBlownVelocity_ReturnValue;             // 0x0234(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          Temp_object_Variable_2;                            // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class ICharacterMovementInterfaceForABP> K2Node_DynamicCast_AsCharacter_Movement_Interface_for_ABP_1; // 0x0248(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_11;                    // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AMonster*                               CallFunc_GetMonster_ReturnValue;                   // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          Temp_object_Variable_3;                            // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable_1;                            // 0x0278(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TScriptInterface<class ICharacterInterface>   K2Node_DynamicCast_AsCharacter_Interface_10;       // 0x0288(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_12;                    // 0x0298(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_299[0x7];                                      // 0x0299(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default;                             // 0x02A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x02B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	EDamageReactionType                           CallFunc_GetReaction_ReactionType_1;               // 0x02C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C1[0x3];                                      // 0x02C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x02C4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x02CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_FindBattleMotionData_ReturnValue;         // 0x02CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Action_Dead_C_ExecuteUbergraph_Action_Dead) == 0x000008, "Wrong alignment on Action_Dead_C_ExecuteUbergraph_Action_Dead");
static_assert(sizeof(Action_Dead_C_ExecuteUbergraph_Action_Dead) == 0x0002D0, "Wrong size on Action_Dead_C_ExecuteUbergraph_Action_Dead");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, EntryPoint) == 0x000000, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::EntryPoint' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, Temp_object_Variable) == 0x000008, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Movement_Interface_for_ABP) == 0x000010, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Movement_Interface_for_ABP' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, Temp_string_Variable) == 0x000028, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::Temp_string_Variable' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_Event_DeltaTime) == 0x000038, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_Event_DeltaTime' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface) == 0x000040, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_1) == 0x000058, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_2) == 0x000068, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetAnimInstance_ReturnValue) == 0x000070, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetAnimInstance_ReturnValue_1) == 0x000078, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetAnimInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetCurrentMoveStateTag_self_CastInput) == 0x000080, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetCurrentMoveStateTag_self_CastInput' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetCurrentMoveStateTag_ReturnValue) == 0x000090, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetCurrentMoveStateTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess) == 0x000098, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::GameplayTagsK2Node_SwitchGameplayTag_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, Temp_bool_IsClosed_Variable) == 0x000099, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, Temp_object_Variable_1) == 0x0000A0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_CustomEvent_Type) == 0x0000A8, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_CustomEvent_Type' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x0000A9, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetEnumeratorName_ReturnValue) == 0x0000AC, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetEnumeratorName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_Conv_NameToString_ReturnValue) == 0x0000B8, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000C8, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_Split_LeftS) == 0x0000D0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_Split_LeftS' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_Split_RightS) == 0x0000E0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_Split_RightS' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_Split_ReturnValue) == 0x0000F0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_Split_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_Concat_StrStr_ReturnValue) == 0x0000F8, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, Temp_bool_Variable) == 0x000108, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_IsTakenFromFront_ReturnValue) == 0x000109, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_IsTakenFromFront_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_2) == 0x000110, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_2' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_3) == 0x000120, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, Temp_bool_Has_Been_Initd_Variable) == 0x000121, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_3) == 0x000128, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_3' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_4) == 0x000138, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetAnimInstance_ReturnValue_2) == 0x000140, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetAnimInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_4) == 0x000148, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_4' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_5) == 0x000158, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_BooleanAND_ReturnValue) == 0x000159, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_5) == 0x000160, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_5' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_6) == 0x000170, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_6) == 0x000178, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_6' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_7) == 0x000188, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_ExecuteAbility_ReturnValue) == 0x000189, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_ExecuteAbility_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_7) == 0x000190, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_7' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_8) == 0x0001A0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_8' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetAnimInstance_ReturnValue_3) == 0x0001A8, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetAnimInstance_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetTargetRotation_ReturnValue) == 0x0001B0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetTargetRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_K2_SetActorRotation_ReturnValue) == 0x0001BC, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_K2_SetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetReaction_ReactionType) == 0x0001BD, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetReaction_ReactionType' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x0001BE, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_8) == 0x0001C0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_8' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_9) == 0x0001D0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_9' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_9) == 0x0001D8, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_9' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_10) == 0x0001E8, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_10' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetLinkType_self_CastInput) == 0x0001F0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetLinkType_self_CastInput' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetLinkType_ReturnValue) == 0x000200, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetLinkType_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetActionResult_ReturnValue) == 0x000204, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetActionResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetBlownVelocity_ReturnValue) == 0x000234, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetBlownVelocity_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, Temp_object_Variable_2) == 0x000240, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Movement_Interface_for_ABP_1) == 0x000248, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Movement_Interface_for_ABP_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_11) == 0x000258, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_11' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetMonster_ReturnValue) == 0x000260, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetMonster_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_IsValid_ReturnValue) == 0x000268, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, Temp_object_Variable_3) == 0x000270, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::Temp_object_Variable_3' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, Temp_string_Variable_1) == 0x000278, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::Temp_string_Variable_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_AsCharacter_Interface_10) == 0x000288, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_AsCharacter_Interface_10' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_DynamicCast_bSuccess_12) == 0x000298, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_DynamicCast_bSuccess_12' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, K2Node_Select_Default) == 0x0002A0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_Concat_StrStr_ReturnValue_1) == 0x0002B0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_GetReaction_ReactionType_1) == 0x0002C0, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_GetReaction_ReactionType_1' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_Conv_StringToName_ReturnValue) == 0x0002C4, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x0002CC, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Action_Dead_C_ExecuteUbergraph_Action_Dead, CallFunc_FindBattleMotionData_ReturnValue) == 0x0002CD, "Member 'Action_Dead_C_ExecuteUbergraph_Action_Dead::CallFunc_FindBattleMotionData_ReturnValue' has a wrong offset!");

}

