#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Action_Dodge

#include "Basic.hpp"

#include "Action_Dodge_classes.hpp"
#include "Action_Dodge_parameters.hpp"


namespace SDK
{

// Function Action_Dodge.Action_Dodge_C.GetGroundDodgeRotationAndType
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FRotator                         Rotation                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// EDodgeType                              Type                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Dodge_C::GetGroundDodgeRotationAndType(struct FRotator* Rotation, EDodgeType* Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "GetGroundDodgeRotationAndType");

	Params::Action_Dodge_C_GetGroundDodgeRotationAndType Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Rotation != nullptr)
		*Rotation = std::move(Parms.Rotation);

	if (Type != nullptr)
		*Type = Parms.Type;
}


// Function Action_Dodge.Action_Dodge_C.GetDodgeRotation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EDodgeType                              DodgeType                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRotator                         Rotation                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UAction_Dodge_C::GetDodgeRotation(EDodgeType* DodgeType, struct FRotator* Rotation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "GetDodgeRotation");

	Params::Action_Dodge_C_GetDodgeRotation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DodgeType != nullptr)
		*DodgeType = Parms.DodgeType;

	if (Rotation != nullptr)
		*Rotation = std::move(Parms.Rotation);
}


// Function Action_Dodge.Action_Dodge_C.Exit
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UAction_Dodge_C::Exit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "Exit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Dodge.Action_Dodge_C.Cancel
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UAction_Dodge_C::Cancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "Cancel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Dodge.Action_Dodge_C.Action
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EDodgeType                              Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Dodge_C::Action(EDodgeType Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "Action");

	Params::Action_Dodge_C_Action Parms{};

	Parms.Type = Type;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Action_Dodge.Action_Dodge_C.Enter_Ground
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UAction_Dodge_C::Enter_Ground()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "Enter_Ground");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Dodge.Action_Dodge_C.Enter_Water
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UAction_Dodge_C::Enter_Water()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "Enter_Water");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Dodge.Action_Dodge_C.Dodge
// (BlueprintCallable, BlueprintEvent)

void UAction_Dodge_C::Dodge()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "Dodge");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Action_Dodge.Action_Dodge_C.Button_Y
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bRelease                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UAction_Dodge_C::Button_Y(bool bRelease)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "Button_Y");

	Params::Action_Dodge_C_Button_Y Parms{};

	Parms.bRelease = bRelease;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Action_Dodge.Action_Dodge_C.ExecuteUbergraph_Action_Dodge
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAction_Dodge_C::ExecuteUbergraph_Action_Dodge(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Action_Dodge_C", "ExecuteUbergraph_Action_Dodge");

	Params::Action_Dodge_C_ExecuteUbergraph_Action_Dodge Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

