#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: All_PirateShip

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass All_PirateShip.All_PirateShip_C
// 0x0008 (0x0238 - 0x0230)
class AAll_PirateShip_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_All_PirateShip(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"All_PirateShip_C">();
	}
	static class AAll_PirateShip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAll_PirateShip_C>();
	}
};
static_assert(alignof(AAll_PirateShip_C) == 0x000008, "Wrong alignment on AAll_PirateShip_C");
static_assert(sizeof(AAll_PirateShip_C) == 0x000238, "Wrong size on AAll_PirateShip_C");
static_assert(offsetof(AAll_PirateShip_C, UberGraphFrame) == 0x000230, "Member 'AAll_PirateShip_C::UberGraphFrame' has a wrong offset!");

}

