#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AN_ReadyToShot

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AN_ReadyToShot.AN_ReadyToShot_C
// 0x0000 (0x0040 - 0x0040)
class UAN_ReadyToShot_C final : public UAnimNotify
{
public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AN_ReadyToShot_C">();
	}
	static class UAN_ReadyToShot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAN_ReadyToShot_C>();
	}
};
static_assert(alignof(UAN_ReadyToShot_C) == 0x000008, "Wrong alignment on UAN_ReadyToShot_C");
static_assert(sizeof(UAN_ReadyToShot_C) == 0x000040, "Wrong size on UAN_ReadyToShot_C");

}

