#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Action_Parkour

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Action_Parkour.BP_Action_Parkour_C
// 0x0010 (0x0140 - 0x0130)
class UBP_Action_Parkour_C final : public UActionStateBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0130(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          Executed;                                          // 0x0138(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void Cancel();
	void Move(const struct FVector& InputVector);
	void Enter_Ground();
	void OnLand();
	void Exit();
	void Enter_Air();
	void Enter_Water();
	void Button_L(bool bRelease);
	void Button_R(bool bRelease);
	void Button_B(bool bRelease);
	void Button_A(bool bRelease);
	void Button_Y(bool bRelease);
	void Button_X(bool bRelease);
	void ExecuteUbergraph_BP_Action_Parkour(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Action_Parkour_C">();
	}
	static class UBP_Action_Parkour_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Action_Parkour_C>();
	}
};
static_assert(alignof(UBP_Action_Parkour_C) == 0x000008, "Wrong alignment on UBP_Action_Parkour_C");
static_assert(sizeof(UBP_Action_Parkour_C) == 0x000140, "Wrong size on UBP_Action_Parkour_C");
static_assert(offsetof(UBP_Action_Parkour_C, UberGraphFrame) == 0x000130, "Member 'UBP_Action_Parkour_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_Action_Parkour_C, Executed) == 0x000138, "Member 'UBP_Action_Parkour_C::Executed' has a wrong offset!");

}

