#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AppPlayerState

#include "Basic.hpp"

#include "BP_AppPlayerState_classes.hpp"
#include "BP_AppPlayerState_parameters.hpp"


namespace SDK
{

// Function BP_AppPlayerState.BP_AppPlayerState_C.ExecuteUbergraph_BP_AppPlayerState
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AppPlayerState_C::ExecuteUbergraph_BP_AppPlayerState(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AppPlayerState_C", "ExecuteUbergraph_BP_AppPlayerState");

	Params::BP_AppPlayerState_C_ExecuteUbergraph_BP_AppPlayerState Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AppPlayerState.BP_AppPlayerState_C.AddExpToPlayer
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ExpValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AppPlayerState_C::AddExpToPlayer(int32 ExpValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AppPlayerState_C", "AddExpToPlayer");

	Params::BP_AppPlayerState_C_AddExpToPlayer Parms{};

	Parms.ExpValue = ExpValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AppPlayerState.BP_AppPlayerState_C.AddExp
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Exp                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AppPlayerState_C::AddExp(int32 Exp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AppPlayerState_C", "AddExp");

	Params::BP_AppPlayerState_C_AddExp Parms{};

	Parms.Exp = Exp;

	UObject::ProcessEvent(Func, &Parms);
}

}

