#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Cannon_00

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Cannon_00.BP_Cannon_00_C
// 0x0008 (0x02B8 - 0x02B0)
class ABP_Cannon_00_C final : public AFieldObjectBase
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Cannon_00_C">();
	}
	static class ABP_Cannon_00_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Cannon_00_C>();
	}
};
static_assert(alignof(ABP_Cannon_00_C) == 0x000008, "Wrong alignment on ABP_Cannon_00_C");
static_assert(sizeof(ABP_Cannon_00_C) == 0x0002B8, "Wrong size on ABP_Cannon_00_C");
static_assert(offsetof(ABP_Cannon_00_C, StaticMesh) == 0x0002B0, "Member 'ABP_Cannon_00_C::StaticMesh' has a wrong offset!");

}

