#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChangeRegionTrigger

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ChangeRegionTrigger.BP_ChangeRegionTrigger_C
// 0x0000 (0x0248 - 0x0248)
class ABP_ChangeRegionTrigger_C final : public AChangeRegionTrigger
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ChangeRegionTrigger_C">();
	}
	static class ABP_ChangeRegionTrigger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ChangeRegionTrigger_C>();
	}
};
static_assert(alignof(ABP_ChangeRegionTrigger_C) == 0x000008, "Wrong alignment on ABP_ChangeRegionTrigger_C");
static_assert(sizeof(ABP_ChangeRegionTrigger_C) == 0x000248, "Wrong size on ABP_ChangeRegionTrigger_C");

}

