#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EvetSystemManagerActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EvetSystemManagerActor.BP_EvetSystemManagerActor_C
// 0x0010 (0x0250 - 0x0240)
class ABP_EvetSystemManagerActor_C final : public AEventSystemManagerActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0240(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_EvetSystemManagerActor(int32 EntryPoint);
	void StartDebugEvent(const class FName EventID);
	void ReceiveBeginPlay();
	void GetBPEventExecuter(class UBP_EventExecter_C** AsBP_Event_Execter);
	void GetBPEventManager(class UBP_EventManager_C** AsBP_Event_Manager);
	void GetBPSequencerController(class UBP_LevelSequenceController_C** AsBP_Level_Sequence_Controller);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EvetSystemManagerActor_C">();
	}
	static class ABP_EvetSystemManagerActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EvetSystemManagerActor_C>();
	}
};
static_assert(alignof(ABP_EvetSystemManagerActor_C) == 0x000008, "Wrong alignment on ABP_EvetSystemManagerActor_C");
static_assert(sizeof(ABP_EvetSystemManagerActor_C) == 0x000250, "Wrong size on ABP_EvetSystemManagerActor_C");
static_assert(offsetof(ABP_EvetSystemManagerActor_C, UberGraphFrame) == 0x000240, "Member 'ABP_EvetSystemManagerActor_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_EvetSystemManagerActor_C, DefaultSceneRoot) == 0x000248, "Member 'ABP_EvetSystemManagerActor_C::DefaultSceneRoot' has a wrong offset!");

}

