#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentManager

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EnvironmentManager.BP_EnvironmentManager_C
// 0x0000 (0x0048 - 0x0048)
class UBP_EnvironmentManager_C final : public UEnvironmentManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EnvironmentManager_C">();
	}
	static class UBP_EnvironmentManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EnvironmentManager_C>();
	}
};
static_assert(alignof(UBP_EnvironmentManager_C) == 0x000008, "Wrong alignment on UBP_EnvironmentManager_C");
static_assert(sizeof(UBP_EnvironmentManager_C) == 0x000048, "Wrong size on UBP_EnvironmentManager_C");

}

