#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EventSystemManager

#include "Basic.hpp"

#include "BP_EventSystemManager_classes.hpp"
#include "BP_EventSystemManager_parameters.hpp"


namespace SDK
{

// Function BP_EventSystemManager.BP_EventSystemManager_C.GetEventManagerActor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_EvetSystemManagerActor_C*     EvetSystemManagerActor                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_EventSystemManager_C::GetEventManagerActor(class ABP_EvetSystemManagerActor_C** EvetSystemManagerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EventSystemManager_C", "GetEventManagerActor");

	Params::BP_EventSystemManager_C_GetEventManagerActor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (EvetSystemManagerActor != nullptr)
		*EvetSystemManagerActor = Parms.EvetSystemManagerActor;
}

}

