#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EvetSystemManagerActor

#include "Basic.hpp"

#include "BP_EvetSystemManagerActor_classes.hpp"
#include "BP_EvetSystemManagerActor_parameters.hpp"


namespace SDK
{

// Function BP_EvetSystemManagerActor.BP_EvetSystemManagerActor_C.ExecuteUbergraph_BP_EvetSystemManagerActor
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EvetSystemManagerActor_C::ExecuteUbergraph_BP_EvetSystemManagerActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EvetSystemManagerActor_C", "ExecuteUbergraph_BP_EvetSystemManagerActor");

	Params::BP_EvetSystemManagerActor_C_ExecuteUbergraph_BP_EvetSystemManagerActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EvetSystemManagerActor.BP_EvetSystemManagerActor_C.StartDebugEvent
// (Event, Public, BlueprintEvent)
// Parameters:
// class FName                             EventID                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EvetSystemManagerActor_C::StartDebugEvent(const class FName EventID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EvetSystemManagerActor_C", "StartDebugEvent");

	Params::BP_EvetSystemManagerActor_C_StartDebugEvent Parms{};

	Parms.EventID = EventID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EvetSystemManagerActor.BP_EvetSystemManagerActor_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_EvetSystemManagerActor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EvetSystemManagerActor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EvetSystemManagerActor.BP_EvetSystemManagerActor_C.GetBPEventExecuter
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UBP_EventExecter_C*               AsBP_Event_Execter                                     (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EvetSystemManagerActor_C::GetBPEventExecuter(class UBP_EventExecter_C** AsBP_Event_Execter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EvetSystemManagerActor_C", "GetBPEventExecuter");

	Params::BP_EvetSystemManagerActor_C_GetBPEventExecuter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsBP_Event_Execter != nullptr)
		*AsBP_Event_Execter = Parms.AsBP_Event_Execter;
}


// Function BP_EvetSystemManagerActor.BP_EvetSystemManagerActor_C.GetBPEventManager
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UBP_EventManager_C*               AsBP_Event_Manager                                     (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EvetSystemManagerActor_C::GetBPEventManager(class UBP_EventManager_C** AsBP_Event_Manager)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EvetSystemManagerActor_C", "GetBPEventManager");

	Params::BP_EvetSystemManagerActor_C_GetBPEventManager Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsBP_Event_Manager != nullptr)
		*AsBP_Event_Manager = Parms.AsBP_Event_Manager;
}


// Function BP_EvetSystemManagerActor.BP_EvetSystemManagerActor_C.GetBPSequencerController
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UBP_LevelSequenceController_C*    AsBP_Level_Sequence_Controller                         (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EvetSystemManagerActor_C::GetBPSequencerController(class UBP_LevelSequenceController_C** AsBP_Level_Sequence_Controller)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EvetSystemManagerActor_C", "GetBPSequencerController");

	Params::BP_EvetSystemManagerActor_C_GetBPSequencerController Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsBP_Level_Sequence_Controller != nullptr)
		*AsBP_Level_Sequence_Controller = Parms.AsBP_Level_Sequence_Controller;
}

}

