#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FastTravelComponent

#include "Basic.hpp"

#include "BP_FastTravelComponent_classes.hpp"
#include "BP_FastTravelComponent_parameters.hpp"


namespace SDK
{

// Function BP_FastTravelComponent.BP_FastTravelComponent_C.ExecuteUbergraph_BP_FastTravelComponent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FastTravelComponent_C::ExecuteUbergraph_BP_FastTravelComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "ExecuteUbergraph_BP_FastTravelComponent");

	Params::BP_FastTravelComponent_C_ExecuteUbergraph_BP_FastTravelComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.OnMoveCore
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FFastTravelInfo                  Info                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_FastTravelComponent_C::OnMoveCore(const struct FFastTravelInfo& Info)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "OnMoveCore");

	Params::BP_FastTravelComponent_C_OnMoveCore Parms{};

	Parms.Info = std::move(Info);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.FadeOutEnd
// (BlueprintCallable, BlueprintEvent)

void UBP_FastTravelComponent_C::FadeOutEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "FadeOutEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.OnMove
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FastTravelComponent_C::OnMove(int32 ID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "OnMove");

	Params::BP_FastTravelComponent_C_OnMove Parms{};

	Parms.ID = ID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.UpdateDebug
// (BlueprintCallable, BlueprintEvent)

void UBP_FastTravelComponent_C::UpdateDebug()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "UpdateDebug");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.FinishFastTravel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AGPACharacter*                    Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FFastTravelInfo                  FastTravelInfo                                         (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_FastTravelComponent_C::FinishFastTravel(class AGPACharacter* Character, const struct FFastTravelInfo& FastTravelInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "FinishFastTravel");

	Params::BP_FastTravelComponent_C_FinishFastTravel Parms{};

	Parms.Character = Character;
	Parms.FastTravelInfo = std::move(FastTravelInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.MoveToPlayer
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FFastTravelInfo                  FastTravelInfo                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class AGPACharacter*                    PlayerActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           CameraActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FastTravelComponent_C::MoveToPlayer(const struct FFastTravelInfo& FastTravelInfo, class AGPACharacter* PlayerActor, class AActor* CameraActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "MoveToPlayer");

	Params::BP_FastTravelComponent_C_MoveToPlayer Parms{};

	Parms.FastTravelInfo = std::move(FastTravelInfo);
	Parms.PlayerActor = PlayerActor;
	Parms.CameraActor = CameraActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FastTravelComponent_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "ReceiveTick");

	Params::BP_FastTravelComponent_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_FastTravelComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.InitializeDebug
// (BlueprintCallable, BlueprintEvent)

void UBP_FastTravelComponent_C::InitializeDebug()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "InitializeDebug");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FastTravelComponent.BP_FastTravelComponent_C.GetFootActor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InputPin                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
// class AActor*                           Out_Hit_Hit_Actor                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBP_FastTravelComponent_C::GetFootActor(class AActor* InputPin, class AActor** Out_Hit_Hit_Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FastTravelComponent_C", "GetFootActor");

	Params::BP_FastTravelComponent_C_GetFootActor Parms{};

	Parms.InputPin = InputPin;

	UObject::ProcessEvent(Func, &Parms);

	if (Out_Hit_Hit_Actor != nullptr)
		*Out_Hit_Hit_Actor = Parms.Out_Hit_Hit_Actor;

	return Parms.ReturnValue;
}

}

