#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FieldManager

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FieldManager.BP_FieldManager_C
// 0x0000 (0x02D8 - 0x02D8)
class UBP_FieldManager_C final : public UFieldManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FieldManager_C">();
	}
	static class UBP_FieldManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FieldManager_C>();
	}
};
static_assert(alignof(UBP_FieldManager_C) == 0x000008, "Wrong alignment on UBP_FieldManager_C");
static_assert(sizeof(UBP_FieldManager_C) == 0x0002D8, "Wrong size on UBP_FieldManager_C");

}

