#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SaveManager

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SaveManager.BP_SaveManager_C
// 0x0000 (0x1318 - 0x1318)
class UBP_SaveManager_C final : public USaveManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SaveManager_C">();
	}
	static class UBP_SaveManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SaveManager_C>();
	}
};
static_assert(alignof(UBP_SaveManager_C) == 0x000008, "Wrong alignment on UBP_SaveManager_C");
static_assert(sizeof(UBP_SaveManager_C) == 0x001318, "Wrong size on UBP_SaveManager_C");

}

