#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTD_IsRivalTeamMonster

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTD_IsRivalTeamMonster.BTD_IsRivalTeamMonster_C
// 0x0000 (0x00A8 - 0x00A8)
class UBTD_IsRivalTeamMonster_C final : public UBTDecorator_BlueprintBase
{
public:
	bool PerformConditionCheckAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTD_IsRivalTeamMonster_C">();
	}
	static class UBTD_IsRivalTeamMonster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTD_IsRivalTeamMonster_C>();
	}
};
static_assert(alignof(UBTD_IsRivalTeamMonster_C) == 0x000008, "Wrong alignment on UBTD_IsRivalTeamMonster_C");
static_assert(sizeof(UBTD_IsRivalTeamMonster_C) == 0x0000A8, "Wrong size on UBTD_IsRivalTeamMonster_C");

}

