#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTS_UpdateFriendThought

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BTS_UpdateThoughtBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BTS_UpdateFriendThought.BTS_UpdateFriendThought_C
// 0x0008 (0x0128 - 0x0120)
class UBTS_UpdateFriendThought_C final : public UBTS_UpdateThoughtBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0120(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BTS_UpdateFriendThought(int32 EntryPoint);
	void ReceiveActivationAI(class AAIController* OwnerController, class APawn* ControlledPawn);
	void ReceiveTickAI(class AAIController* OwnerController, class APawn* ControlledPawn, float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BTS_UpdateFriendThought_C">();
	}
	static class UBTS_UpdateFriendThought_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTS_UpdateFriendThought_C>();
	}
};
static_assert(alignof(UBTS_UpdateFriendThought_C) == 0x000008, "Wrong alignment on UBTS_UpdateFriendThought_C");
static_assert(sizeof(UBTS_UpdateFriendThought_C) == 0x000128, "Wrong size on UBTS_UpdateFriendThought_C");
static_assert(offsetof(UBTS_UpdateFriendThought_C, UberGraphFrame) == 0x000120, "Member 'UBTS_UpdateFriendThought_C::UberGraphFrame' has a wrong offset!");

}

