#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_NPCMoveTo

#include "Basic.hpp"

#include "BTTask_NPCMoveTo_classes.hpp"
#include "BTTask_NPCMoveTo_parameters.hpp"


namespace SDK
{

// Function BTTask_NPCMoveTo.BTTask_NPCMoveTo_C.ExecuteUbergraph_BTTask_NPCMoveTo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_NPCMoveTo_C::ExecuteUbergraph_BTTask_NPCMoveTo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_NPCMoveTo_C", "ExecuteUbergraph_BTTask_NPCMoveTo");

	Params::BTTask_NPCMoveTo_C_ExecuteUbergraph_BTTask_NPCMoveTo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_NPCMoveTo.BTTask_NPCMoveTo_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_NPCMoveTo_C::ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_NPCMoveTo_C", "ReceiveExecuteAI");

	Params::BTTask_NPCMoveTo_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_NPCMoveTo.BTTask_NPCMoveTo_C.OnSuccess_2ECBD2D846B1883797C14CB28BE6CBDF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_NPCMoveTo_C::OnSuccess_2ECBD2D846B1883797C14CB28BE6CBDF(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_NPCMoveTo_C", "OnSuccess_2ECBD2D846B1883797C14CB28BE6CBDF");

	Params::BTTask_NPCMoveTo_C_OnSuccess_2ECBD2D846B1883797C14CB28BE6CBDF Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_NPCMoveTo.BTTask_NPCMoveTo_C.OnFail_2ECBD2D846B1883797C14CB28BE6CBDF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_NPCMoveTo_C::OnFail_2ECBD2D846B1883797C14CB28BE6CBDF(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_NPCMoveTo_C", "OnFail_2ECBD2D846B1883797C14CB28BE6CBDF");

	Params::BTTask_NPCMoveTo_C_OnFail_2ECBD2D846B1883797C14CB28BE6CBDF Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_NPCMoveTo.BTTask_NPCMoveTo_C.StopMove
// (Public, BlueprintCallable, BlueprintEvent)

void UBTTask_NPCMoveTo_C::StopMove()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_NPCMoveTo_C", "StopMove");

	UObject::ProcessEvent(Func, nullptr);
}

}

