#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FieldLink_Search

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FieldLink_Search.FieldLink_Search_C
// 0x0010 (0x0158 - 0x0148)
class UFieldLink_Search_C final : public UFieldLinkBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0148(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          Executed;                                          // 0x0150(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void Enter_Ground();
	void Cancel();
	void Enter_Air();
	void ExecuteUbergraph_FieldLink_Search(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FieldLink_Search_C">();
	}
	static class UFieldLink_Search_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFieldLink_Search_C>();
	}
};
static_assert(alignof(UFieldLink_Search_C) == 0x000008, "Wrong alignment on UFieldLink_Search_C");
static_assert(sizeof(UFieldLink_Search_C) == 0x000158, "Wrong size on UFieldLink_Search_C");
static_assert(offsetof(UFieldLink_Search_C, UberGraphFrame) == 0x000148, "Member 'UFieldLink_Search_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UFieldLink_Search_C, Executed) == 0x000150, "Member 'UFieldLink_Search_C::Executed' has a wrong offset!");

}

