#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_AtkCorrect

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_AtkCorrect.GC_AtkCorrect_C
// 0x0010 (0x02B8 - 0x02A8)
class AGC_AtkCorrect_C final : public ADarwinGameplayCue
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void ReceiveDestroyed();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ExecuteUbergraph_GC_AtkCorrect(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_AtkCorrect_C">();
	}
	static class AGC_AtkCorrect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_AtkCorrect_C>();
	}
};
static_assert(alignof(AGC_AtkCorrect_C) == 0x000008, "Wrong alignment on AGC_AtkCorrect_C");
static_assert(sizeof(AGC_AtkCorrect_C) == 0x0002B8, "Wrong size on AGC_AtkCorrect_C");
static_assert(offsetof(AGC_AtkCorrect_C, UberGraphFrame) == 0x0002A8, "Member 'AGC_AtkCorrect_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AGC_AtkCorrect_C, DefaultSceneRoot) == 0x0002B0, "Member 'AGC_AtkCorrect_C::DefaultSceneRoot' has a wrong offset!");

}

