#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Poison

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Poison.GC_Poison_C
// 0x0010 (0x02B8 - 0x02A8)
class AGC_Poison_C : public ADarwinGameplayCue
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class AEffectBase*                            Effect;                                            // 0x02B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Poison_C">();
	}
	static class AGC_Poison_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Poison_C>();
	}
};
static_assert(alignof(AGC_Poison_C) == 0x000008, "Wrong alignment on AGC_Poison_C");
static_assert(sizeof(AGC_Poison_C) == 0x0002B8, "Wrong size on AGC_Poison_C");
static_assert(offsetof(AGC_Poison_C, DefaultSceneRoot) == 0x0002A8, "Member 'AGC_Poison_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AGC_Poison_C, Effect) == 0x0002B0, "Member 'AGC_Poison_C::Effect' has a wrong offset!");

}

