#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Sleep

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Sleep.GC_Sleep_C
// 0x0010 (0x02B8 - 0x02A8)
class AGC_Sleep_C final : public ADarwinGameplayCue
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class AEffectBase*                            Effect;                                            // 0x02B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Sleep_C">();
	}
	static class AGC_Sleep_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Sleep_C>();
	}
};
static_assert(alignof(AGC_Sleep_C) == 0x000008, "Wrong alignment on AGC_Sleep_C");
static_assert(sizeof(AGC_Sleep_C) == 0x0002B8, "Wrong size on AGC_Sleep_C");
static_assert(offsetof(AGC_Sleep_C, DefaultSceneRoot) == 0x0002A8, "Member 'AGC_Sleep_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AGC_Sleep_C, Effect) == 0x0002B0, "Member 'AGC_Sleep_C::Effect' has a wrong offset!");

}

