#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_SkillChainDamage

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_SkillChainDamage.GE_SkillChainDamage_C
// 0x0000 (0x07C0 - 0x07C0)
class UGE_SkillChainDamage_C final : public UBattleDamageGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_SkillChainDamage_C">();
	}
	static class UGE_SkillChainDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SkillChainDamage_C>();
	}
};
static_assert(alignof(UGE_SkillChainDamage_C) == 0x000008, "Wrong alignment on UGE_SkillChainDamage_C");
static_assert(sizeof(UGE_SkillChainDamage_C) == 0x0007C0, "Wrong size on UGE_SkillChainDamage_C");

}

