#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Commonmenu_ItemName

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Commonmenu_ItemName.W_Commonmenu_ItemName_C
// 0x0008 (0x0498 - 0x0490)
class UW_Commonmenu_ItemName_C final : public UUICommonmenu_ItemName
{
public:
	class UImage*                                 NameBase;                                          // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_Commonmenu_ItemName_C">();
	}
	static class UW_Commonmenu_ItemName_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Commonmenu_ItemName_C>();
	}
};
static_assert(alignof(UW_Commonmenu_ItemName_C) == 0x000008, "Wrong alignment on UW_Commonmenu_ItemName_C");
static_assert(sizeof(UW_Commonmenu_ItemName_C) == 0x000498, "Wrong size on UW_Commonmenu_ItemName_C");
static_assert(offsetof(UW_Commonmenu_ItemName_C, NameBase) == 0x000490, "Member 'UW_Commonmenu_ItemName_C::NameBase' has a wrong offset!");

}

