#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Commonmenu_01

#include "Basic.hpp"

#include "W_Commonmenu_01_classes.hpp"
#include "W_Commonmenu_01_parameters.hpp"


namespace SDK
{

// Function W_Commonmenu_01.W_Commonmenu_01_C.ExecuteUbergraph_W_Commonmenu_01
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Commonmenu_01_C::ExecuteUbergraph_W_Commonmenu_01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Commonmenu_01_C", "ExecuteUbergraph_W_Commonmenu_01");

	Params::W_Commonmenu_01_C_ExecuteUbergraph_W_Commonmenu_01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Commonmenu_01.W_Commonmenu_01_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_Commonmenu_01_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Commonmenu_01_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

