#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Field_IconQuestline

#include "Basic.hpp"

#include "W_Field_IconQuestline_classes.hpp"
#include "W_Field_IconQuestline_parameters.hpp"


namespace SDK
{

// Function W_Field_IconQuestline.W_Field_IconQuestLine_C.SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_3
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Field_IconQuestLine_C::SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Field_IconQuestLine_C", "SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Field_IconQuestline.W_Field_IconQuestLine_C.SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_2
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Field_IconQuestLine_C::SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Field_IconQuestLine_C", "SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Field_IconQuestline.W_Field_IconQuestLine_C.SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_1
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Field_IconQuestLine_C::SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Field_IconQuestLine_C", "SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Field_IconQuestline.W_Field_IconQuestLine_C.SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_0
// (Public, BlueprintCallable, BlueprintEvent)

void UW_Field_IconQuestLine_C::SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Field_IconQuestLine_C", "SequenceEvent__ENTRYPOINTW_Field_IconQuestLine_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Field_IconQuestline.W_Field_IconQuestLine_C.StartQuestAnimEnd
// (BlueprintCallable, BlueprintEvent)

void UW_Field_IconQuestLine_C::StartQuestAnimEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Field_IconQuestLine_C", "StartQuestAnimEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Field_IconQuestline.W_Field_IconQuestLine_C.StampWait
// (BlueprintCallable, BlueprintEvent)

void UW_Field_IconQuestLine_C::StampWait()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Field_IconQuestLine_C", "StampWait");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Field_IconQuestline.W_Field_IconQuestLine_C.StampAnimEnd
// (BlueprintCallable, BlueprintEvent)

void UW_Field_IconQuestLine_C::StampAnimEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Field_IconQuestLine_C", "StampAnimEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Field_IconQuestline.W_Field_IconQuestLine_C.ClearQuestAnimEnd
// (BlueprintCallable, BlueprintEvent)

void UW_Field_IconQuestLine_C::ClearQuestAnimEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Field_IconQuestLine_C", "ClearQuestAnimEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Field_IconQuestline.W_Field_IconQuestLine_C.ExecuteUbergraph_W_Field_IconQuestLine
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Field_IconQuestLine_C::ExecuteUbergraph_W_Field_IconQuestLine(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Field_IconQuestLine_C", "ExecuteUbergraph_W_Field_IconQuestLine");

	Params::W_Field_IconQuestLine_C_ExecuteUbergraph_W_Field_IconQuestLine Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

