#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Itemmenu

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Itemmenu.W_Itemmenu_C
// 0x0010 (0x0590 - 0x0580)
class UW_Itemmenu_C final : public UUIItemmenu
{
public:
	class UW_LeftMenu_C*                          W_LeftMenu;                                        // 0x0580(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Under_Button_C*                      W_Under_Button;                                    // 0x0588(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_Itemmenu_C">();
	}
	static class UW_Itemmenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Itemmenu_C>();
	}
};
static_assert(alignof(UW_Itemmenu_C) == 0x000010, "Wrong alignment on UW_Itemmenu_C");
static_assert(sizeof(UW_Itemmenu_C) == 0x000590, "Wrong size on UW_Itemmenu_C");
static_assert(offsetof(UW_Itemmenu_C, W_LeftMenu) == 0x000580, "Member 'UW_Itemmenu_C::W_LeftMenu' has a wrong offset!");
static_assert(offsetof(UW_Itemmenu_C, W_Under_Button) == 0x000588, "Member 'UW_Itemmenu_C::W_Under_Button' has a wrong offset!");

}

