#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_KnowledgeMenu_Content01

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_KnowledgeMenu_Content01.W_KnowledgeMenu_Content01_C
// 0x0010 (0x04A0 - 0x0490)
class UW_KnowledgeMenu_Content01_C final : public UDarwinUserWidget
{
public:
	class UImage*                                 Tips;                                              // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TipsBase;                                          // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_KnowledgeMenu_Content01_C">();
	}
	static class UW_KnowledgeMenu_Content01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_KnowledgeMenu_Content01_C>();
	}
};
static_assert(alignof(UW_KnowledgeMenu_Content01_C) == 0x000008, "Wrong alignment on UW_KnowledgeMenu_Content01_C");
static_assert(sizeof(UW_KnowledgeMenu_Content01_C) == 0x0004A0, "Wrong size on UW_KnowledgeMenu_Content01_C");
static_assert(offsetof(UW_KnowledgeMenu_Content01_C, Tips) == 0x000490, "Member 'UW_KnowledgeMenu_Content01_C::Tips' has a wrong offset!");
static_assert(offsetof(UW_KnowledgeMenu_Content01_C, TipsBase) == 0x000498, "Member 'UW_KnowledgeMenu_Content01_C::TipsBase' has a wrong offset!");

}

