#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_NetWork_WinTerms_Root

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_NetWork_WinTerms_Root.W_NetWork_WinTerms_Root_C
// 0x0000 (0x04E0 - 0x04E0)
class UW_NetWork_WinTerms_Root_C final : public UUINetWorkWinTerms_Root
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_NetWork_WinTerms_Root_C">();
	}
	static class UW_NetWork_WinTerms_Root_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_NetWork_WinTerms_Root_C>();
	}
};
static_assert(alignof(UW_NetWork_WinTerms_Root_C) == 0x000008, "Wrong alignment on UW_NetWork_WinTerms_Root_C");
static_assert(sizeof(UW_NetWork_WinTerms_Root_C) == 0x0004E0, "Wrong size on UW_NetWork_WinTerms_Root_C");

}

