#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_NowMoney

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_NowMoney.W_NowMoney_C
// 0x0010 (0x04A0 - 0x0490)
class UW_NowMoney_C final : public UUINowMoney
{
public:
	class UImage*                                 Money_Icon;                                        // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Moneybase;                                         // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_NowMoney_C">();
	}
	static class UW_NowMoney_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_NowMoney_C>();
	}
};
static_assert(alignof(UW_NowMoney_C) == 0x000008, "Wrong alignment on UW_NowMoney_C");
static_assert(sizeof(UW_NowMoney_C) == 0x0004A0, "Wrong size on UW_NowMoney_C");
static_assert(offsetof(UW_NowMoney_C, Money_Icon) == 0x000490, "Member 'UW_NowMoney_C::Money_Icon' has a wrong offset!");
static_assert(offsetof(UW_NowMoney_C, Moneybase) == 0x000498, "Member 'UW_NowMoney_C::Moneybase' has a wrong offset!");

}

