#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_QuestOrder_Root

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_QuestOrder_Root.W_QuestOrder_Root_C
// 0x0008 (0x0520 - 0x0518)
class UW_QuestOrder_Root_C final : public UUIQuestOrder_Root
{
public:
	class UImage*                                 ImageCapture;                                      // 0x0518(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_QuestOrder_Root_C">();
	}
	static class UW_QuestOrder_Root_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_QuestOrder_Root_C>();
	}
};
static_assert(alignof(UW_QuestOrder_Root_C) == 0x000008, "Wrong alignment on UW_QuestOrder_Root_C");
static_assert(sizeof(UW_QuestOrder_Root_C) == 0x000520, "Wrong size on UW_QuestOrder_Root_C");
static_assert(offsetof(UW_QuestOrder_Root_C, ImageCapture) == 0x000518, "Member 'UW_QuestOrder_Root_C::ImageCapture' has a wrong offset!");

}

