#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_QuestMenu_Root

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_QuestMenu_Root.W_QuestMenu_Root_C
// 0x0000 (0x04D8 - 0x04D8)
class UW_QuestMenu_Root_C final : public UUIQuestMenu_Root
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_QuestMenu_Root_C">();
	}
	static class UW_QuestMenu_Root_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_QuestMenu_Root_C>();
	}
};
static_assert(alignof(UW_QuestMenu_Root_C) == 0x000008, "Wrong alignment on UW_QuestMenu_Root_C");
static_assert(sizeof(UW_QuestMenu_Root_C) == 0x0004D8, "Wrong size on UW_QuestMenu_Root_C");

}

