#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Sign_IconDamageComposite

#include "Basic.hpp"

#include "DarwinGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Sign_IconDamageComposite.W_Sign_IconDamageComposite_C
// 0x0000 (0x05C0 - 0x05C0)
class UW_Sign_IconDamageComposite_C final : public UUISign_IconDamageComposite
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_Sign_IconDamageComposite_C">();
	}
	static class UW_Sign_IconDamageComposite_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Sign_IconDamageComposite_C>();
	}
};
static_assert(alignof(UW_Sign_IconDamageComposite_C) == 0x000010, "Wrong alignment on UW_Sign_IconDamageComposite_C");
static_assert(sizeof(UW_Sign_IconDamageComposite_C) == 0x0005C0, "Wrong size on UW_Sign_IconDamageComposite_C");

}

